### ISSUE TITLE
jsperf init throws 'spawn npm ENOENT' on Windows

### ISSUE THREAD

**Issue by bisubus** [OrKoN/jsperf#1]
`jsperf init` throws 

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:855:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickCallback (node.js:369:17)
    at Function.Module.runMain (module.js:432:11)
    at startup (node.js:141:18)
    at node.js:980:3
```

and results in empty project json (no `benchmark beautify-benchmark` dev dependencies):

```
  {
    "name": "jsperf.com",
    "version": "0.1.0",
    "private": true,
    "description": "Run jsperf.com tests locally with your NodeJS version",
    "dependencies": {
    },
    "devDependencies": {
    }
  }
```

**Comment by OrKoN** [comment]
I don't have a Windows here. Could you assist in testing? 

After some googling it turns out that native node's spawn does not work correctly on Windows. I will try to use instead https://github.com/IndigoUnited/node-cross-spawn-async

**Comment by bisubus** [comment]
@OrKoN That's correct, `cross-spawn-async` is commonly used as drop-in replacement for native spawn, there shouldn't be any problems with that if there are no other platform-specific issues. Sure, I will confirm that everything is ok.

**Comment by OrKoN** [comment]
@bisubus I have releases 0.2.0 that should fix this. Please confirm. And thanks for reporting.

**Comment by bisubus** [comment]
@OrKoN Thank you for quick response, everything works like a charm in 0.2.0 so far.
