### ISSUE TITLE
Add support for CLI options

### ISSUE THREAD

**Issue by bisubus** [OrKoN/jsperf#2]
Currently CLI doesn't accept options for `opts` parameter in `JsPerf` constructor (e.g. `host`).

Can the support for them be added to CLI?

**Comment by OrKoN** [comment]
Yes, feel free to submit a PR or I will work on it when I have time. What's your use case for this?

**Comment by bisubus** [comment]
@OrKoN Thanks, I will PR if I will come up with something, currently I have to call JsPerf constructor directly.

I'm mostly working on our local copy of jsperf.

**Comment by OrKoN** [comment]
@bisubus I have added --host parameter to the cli. Please try if this works for you.
